# Generated by Django 5.0.1 on 2024-11-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_alter_codingquestion_question'),
        ('students', '0006_codingsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.question'),
        ),
    ]
