# Generated by Django 5.0.1 on 2024-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_codingsubmission_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
    ]
