version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: quiz
    restart: always
    env_file:
      - .env
    ports:
      - "10000:10000"
