# Generated by Django 5.0.1 on 2024-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_rename_text_question_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_options',
        ),
        migrations.AddField(
            model_name='question',
            name='option_1_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4_is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
