# Generated by Django 5.0.1 on 2024-07-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_remove_question_option_1_and_more'),
        ('students', '0002_quizresult_delete_question_delete_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
