# Generated by Django 5.0.1 on 2024-07-04 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(default='2024-07-31 23:59:59'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='students',
            field=models.ManyToManyField(related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
