# Generated by Django 5.0.1 on 2024-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_quiz_due_date_quiz_students'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assigned_students',
            field=models.ManyToManyField(related_name='quizzes', to='students.student'),
        ),
    ]
