# Generated by Django 5.0.1 on 2024-07-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_remove_question_correct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_1_is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2_is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3_is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4_is_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='students',
        ),
    ]
