# Generated by Django 5.0.1 on 2024-07-20 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
