# Generated by Django 5.0.1 on 2024-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_quiz_is_available_to_students_alter_quiz_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2'), ('choice3', 'Choice 3'), ('choice4', 'Choice 4')], default='choice1', max_length=10),
        ),
    ]
