# Generated by Django 5.0.1 on 2024-11-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_quiz_allowed_students_quiz_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
