# Generated by Django 5.0.1 on 2024-11-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_quizupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizupload',
            name='quiz_name',
            field=models.CharField(default='default_quiz_name', max_length=255),
        ),
    ]
