# Generated by Django 5.0.1 on 2024-11-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_quizupload_description_quizupload_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('function_name', models.CharField(max_length=255)),
                ('test_case_1_input', models.TextField()),
                ('test_case_1_output', models.TextField()),
                ('test_case_2_input', models.TextField()),
                ('test_case_2_output', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admins.question')),
            ],
        ),
    ]
