# Generated by Django 5.0.1 on 2024-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_codingquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI_CORRECT', 'Multi-Correct'), ('SHORT', 'Short Answer'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill-in-the-Blank'), ('CODING', 'Coding')], max_length=20),
        ),
    ]
