# Generated by Django 5.0.1 on 2024-11-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.question'),
        ),
    ]
