# Generated by Django 5.0.1 on 2024-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_quizresult_delete_question_delete_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
