# Generated by Django 5.0.1 on 2024-10-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
